### ISSUE TITLE
Issue with the Connection to QM Form in Unity.

### ISSUE THREAD

**Issue by Diallo** [VisualMQ/VisualMQ#15]
Intermittent bug: Reproduced by trying to fill in the QM1 Details.

More details TBA as I see it occur. 

![image](https://user-images.githubusercontent.com/33268295/124565147-9f2d9980-de39-11eb-9890-7ead5552af1b.png)

**Comment by lukasotocerny** [comment]
+1 I experienced it as well. It happens when you click on smaller texts below the text input fields, e.g. "The name of the Queue Manager"

**Comment by yuexu-98** [comment]
I will have a closer look later

**Comment by yuexu-98** [comment]
- [x] Authentication Window Label Issue
- [x] Other Details Window (check)

**Comment by yuexu-98** [comment]
Fixed: this is because these objects were linked to the dropdown objects. 😂
