### ISSUE TITLE
Authentication Error Handling

### ISSUE THREAD

**Issue by yuexu-98** [VisualMQ/VisualMQ#16]
Unable to deal with authentication failure situation.
E.g., Use the Wrong QM name.

**Comment by yuexu-98** [comment]
![image](https://user-images.githubusercontent.com/45183874/124596794-98634e80-de5a-11eb-9de7-cf937d111af9.png)
Can not tell the difference from the response

**Comment by yuexu-98** [comment]
![image](https://user-images.githubusercontent.com/45183874/124597602-964dbf80-de5b-11eb-8bd6-021692ad33ff.png)

**Comment by phillip-tian** [comment]
I will take a look at the code and get back to you.

**Comment by phillip-tian** [comment]
Fixed.
