### ISSUE TITLE
Error when retriving messages fron alias queue and remote queue

### ISSUE THREAD

**Issue by yuexu-98** [VisualMQ/VisualMQ#29]
- [x] Disable "generateMesaage" for alias queue and remote queue
- [x] Duplicate Row Item Issue: Need to add destroy functions.

**Comment by phillip-tian** [comment]
check for queue.holdsMessage == true before retriving message list.

**Comment by lukasotocerny** [comment]
Solved in https://github.com/VisualMQ/VisualMQ/pull/79
