### ISSUE TITLE
Message list rendering issue

### ISSUE THREAD

**Issue by lukasotocerny** [VisualMQ/VisualMQ#30]
Similarly as with the list of queues, there is a rendering issue when clicking on a message list for a second time

![Screenshot 2021-07-13 at 8 42 47](https://user-images.githubusercontent.com/13408109/125404122-921f2600-e3b6-11eb-9390-3dc0854bf410.png)

**Comment by yuexu-98** [comment]
Fixed

**Comment by yuexu-98** [comment]
Add destroy object function to message window
