### ISSUE TITLE
Incorrect mouse click action when two clickable objects overlap.

### ISSUE THREAD

**Issue by phillip-tian** [VisualMQ/VisualMQ#38]
One small bug I encountered: when creating a second QM inside our app, if the connection window and the first QM visualization overlap, a mouse click in the connection window will be captured by the QM visualization in the background. 
<img width="964" alt="Screen Shot 2021-07-14 at 10 24 49 PM" src="https://user-images.githubusercontent.com/25778414/125695085-9e7d32bb-8ee7-4d1f-9e7c-1dbbbcefb568.png">

So in the screenshot above, if I click on the input box for apikey, and the current viewpoint has DEV.QUEUE.3 in the background, the mouse click on the apikey input box would bring up the QM info panel.

**Comment by yuexu-98** [comment]
Fixed.
Add a checking condition in the Queue.cs, OnMouseUp()
