### ISSUE TITLE
Using async function incorrectly

### ISSUE THREAD

**Issue by lukasotocerny** [VisualMQ/VisualMQ#50]
Within the MQ library we are sending HTTP requests via `GetAsync` function. But we are using it synchronously, without `await`. This seems fishy. Not sure how come it is working and how .NET handles this, but it could potentially cause problems.

**Comment by phillip-tian** [comment]
In .NET, ```GetAsync``` returns an object of type ```Task<HttpResponseMessage>```, which represents an asynchronous operation that can return a value. (an ```HttpResponseMessge``` in this case) 
We store the return value of the task by accessing ```GetAsync(endpoint).Result```, and the .NET documentation specifies that "Accessing the property(Result)...blocks the calling thread until the asynchronous operation is complete; **it is equivalent to calling the Wait method**." Therefore the library code is actually running synchronously as expected.

Reference: [HttpClient.GetAsync Method](https://docs.microsoft.com/en-us/dotnet/api/system.net.http.httpclient.getasync?view=net-5.0#System_Net_Http_HttpClient_GetAsync_System_String_), [Task<TResult>.Result Property](https://docs.microsoft.com/en-us/dotnet/api/system.threading.tasks.task-1.result?view=net-5.0#remarks)

**Comment by lukasotocerny** [comment]
That's great then. Thanks for checking this out.
