### ISSUE TITLE
QM Block Reflecting Too Much Directional Light

### ISSUE THREAD

**Issue by phillip-tian** [VisualMQ/VisualMQ#75]
<img width="807" alt="Screen Shot 2021-08-10 at 9 12 31 PM" src="https://user-images.githubusercontent.com/25778414/128931070-5944c666-f451-4869-8d37-f774b6f36337.png">

As shown above, the blocks are so reflective that at view angles like this, it is impossible to see the names of the GameObjects.

@huyifanx I am assigning you to take a look at whether this could be solved by tweaking the parameters of the block material or adjusting Directional Light in Unity scene.

**Comment by phillip-tian** [comment]
@huyifanx I played around with the settings of the Directional Light, and if we are happy with how things look right now I would suggest working on other tasks at hand instead.

**Comment by lukasotocerny** [comment]
Solved in https://github.com/VisualMQ/VisualMQ/pull/97
Queues still reflect a lot of light as they are from a more metallic material, so little tweaks with materials and still encouraged.
