### ISSUE TITLE
Add Connection Info for Sender Channel in the Side Panel

### ISSUE THREAD

**Issue by phillip-tian** [VisualMQ/VisualMQ#76]
Sender channels have a non-empty property called ```conname```:
```"conname": "qm2-3628.qm.eu-gb.mq.appdomain.cloud(31918)"```
In our MQ library, it is stored in this way:
```((SenderChannel)channel).connectionName```
It would be nice to display this piece of information in the side panel when the user clicks on sender channels.

**Comment by yuexu-98** [comment]
Added
